### ISSUE TITLE
天朝境内引用 fonts.googleapi.com 中的字体有可能会导致ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by liuqun** [zouyaoji/vue-cesium-v2#2]
https://github.com/zouyaoji/vue-cesium-v2/blob/d94e01d32e5734be9907159845b792d2e0146976/src/assets/styles/common/_variables.scss#L1-L2

目前我测试山东电信是可以访问googleapi.com的
![image](https://user-images.githubusercontent.com/64795/124219204-743c0080-db2e-11eb-8052-a669d0a53e4a.png)

但还是建议替换掉 fonts.googleapi.com 中的特殊字体，改为各浏览器默认的中英文字体。
另外内网环境肯定是访问不到googleapi.com的。

**Comment by zouyaoji** [comment]
国内一般用哪些？

**Comment by liuqun** [comment]
一、如何优雅的选择字体(font-family)
- https://www.cnblogs.com/kenshinobiy/p/7398730.html


二、如何最有效的解决Google公共库&字体库被屏蔽的问题？ - Hao Lee的回答 - 知乎
- https://www.zhihu.com/question/24955477/answer/120232550

三、奇虎360不再提供谷歌字体服务
- https://wangzhan.qianxin.com/notice/detail4
![image](https://user-images.githubusercontent.com/64795/124431507-04827b80-dda3-11eb-87c6-b1f43fc1e6f1.png)

**Comment by liuqun** [comment]
- https://www.stackoverflow.wiki/blog/articles/2020/04/23/1587654872933.html
离线使用 Google Fonts----goofoffline下载生成离线字体库

```
npm install -g google-fonts-offline
```

```
goofoffline "https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,400italic,600"
```
查看下当前目录的文件，你会发现多出了一个 fonts 文件夹：
fonts      index.html

进入 fonts 文件夹里面有一个fonts.css

现在，我们只需要引用 fonts.css 到 HTML 中就可以了。



同理再下载
```
goofoffline "https://fonts.googleapis.com/css?family=Lato:400,700"
```

**Comment by zouyaoji** [comment]
我看vue3的版本我都没这么用了，也想不起为啥加了这2行了。下个版本我打算直接把那两行注释了。
